[tool.poetry]
name = "msys2-web"
version = "0.1.0"
description = ""
authors = ["Christoph Reiter <reiter.christoph@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.7"
httpx = "^0.13.3"
fastapi = "^0.59.0"
uvicorn = "^0.11.5"
aiofiles = "^0.5.0"
jinja2 = "^2.11.2"
fastapi-etag = "^0.2.1"
pgpdump = "^1.5"

[tool.poetry.dev-dependencies]
mypy = "^0.782"
flake8 = "^3.8.2"
pytest = "^5.4.2"
requests = "^2.23.0"
respx = "^0.11.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
