[tool.poetry]
name = "msys2-web"
version = "0.1.0"
description = ""
authors = ["Christoph Reiter <reiter.christoph@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.7"
httpx = {extras = ["http2"], version = "^0.18.1"}
fastapi = "^0.65.1"
uvicorn = {extras = ["standard"], version = "^0.14.0"}
aiofiles = "^0.7.0"
jinja2 = "^3.0.0"
fastapi-etag = "^0.3.0"
pgpdump = "^1.5"
gunicorn = "^20.0.4"
aiolimiter = "^1.0.0-beta.1"

[tool.poetry.dev-dependencies]
mypy = "^0.902"
flake8 = "^3.8.2"
pytest = "^6.0.1"
requests = "^2.23.0"
respx = "^0.17.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
